### ISSUE TITLE
Is there a reason crypto.subtle is missing in most polyfills including this one?

### ISSUE THREAD

**Issue by shamilovtim** [browserify/crypto-browserify#221]
Hello,

We are using a project which needs `crypto.browserify` (or its derivatives and the packages it has inspired). However we have hit a problem: crypto.subtle isn't polyfilled. This is a source of incompatibility with all projects that depend on crypto.subtle. What can we do to get crypto.subtle in polyfills?

**Comment by ljharb** [comment]
Not that I know of. A PR to add it, with tests, would probably be what's needed.

#203 seems related.
