### ISSUE TITLE
Security vulnerability being surfaced around elliptic sub dependencies

### ISSUE THREAD

**Issue by jennifer-shehane** [browserify/crypto-browserify#234]
This vulnerability report surfaces `elliptic` as having a critical vulnerability. This is a sub dependency of some dependencies in this package. https://security.snyk.io/vuln/SNYK-JS-ELLIPTIC-7577916

Please update the dependencies to have the updated `elliptic` package as their deps. 

```
"browserify-sign": "^4.2.3", // has elliptic <6.5.7 as a dep
"create-ecdh": "^4.0.4", // has elliptic <6.5.7 as a dep
```

This was highlighted in our Snyk security scan of our product that relies on this package.

Elliptic 6.5.7 release: https://github.com/indutny/elliptic/commit/3e46a48fdd2ef2f89593e5e058d85530578c9761

**Comment by ljharb** [comment]
Everything in the tree uses `^` to depend on everything, so *no action is needed* in the graph, and you shouldn't be filing these kinds of issues. Just update your lockfile.
