### ISSUE TITLE
version 3.12.1 fails because of process is not defined error

### ISSUE THREAD

**Issue by alexmalev** [browserify/crypto-browserify#236]
version 3.12.0 works well.
after upgrade to 3.12.1, the update to this  dependency `"browserify-sign": "^4.2.3",` now causes the above error
`process is not defined` on this line `var asyncWrite = !process.browser` of `broswerify-sign -> readable-stream`

![Image](https://github.com/user-attachments/assets/e5cdff8d-4f77-4b06-b03f-f7a5d9d85af9)

environment chrome extension built with vite

**Comment by ljharb** [comment]
Then the problem is in vite - a working node module bundler provides a process shim.

**Comment by alexmalev** [comment]
> Then the problem is in vite - a working node module bundler provides a process shim.

thanks you were right.

using "vite-plugin-node-polyfills" fixed the problem altogether

**Comment by lessGameMoreStudy** [comment]
webpack 5 also have this problem!
